/**
 *
 * @module      mod_nextblocks/env
 * @copyright   2023 Duarte Pereira<dg.pereira@campus.fct.unl.pt>
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/* globals javascript */

/**
 * Injects the box for inserting the program input below the blockly area
 * @param {Number} i the index of the input box, to avoid repetition of ids
 */
export const injectInputBox = (i) => {
    // Create input box for program input
    const inputBox = document.createElement('input');
    inputBox.setAttribute('type', 'text');
    inputBox.setAttribute('id', 'programInputBox' + i);

    // Create button to submit input
    const submitButton = document.createElement('button');
    submitButton.setAttribute('id', 'programInputButton' + i);
    submitButton.setAttribute('type', 'button');
    submitButton.innerHTML = 'Submit';

    // Insert input box and button below blockly area
    const blocklyDiv = document.getElementById('blocklyDiv');
    blocklyDiv.insertAdjacentElement('afterend', inputBox);
    inputBox.insertAdjacentElement('afterend', submitButton);
};

/**
 * Inserts the new program code in the code div below the blockly area, replacing the old one if it exists
 * @param {String} code the new program code to be displayed
 */
export const replaceCode = (code) => {
    const codeDiv = document.getElementById('codeDiv');
    codeDiv.innerHTML = formatCodeHTML(code);
};

/**
 * Formats the code with correct html structure to be displayed in the code div
 * TODO: implement this function
 * @param {String} code the code text to be formatted (string literal)
 * @returns {String} the formatted code
 */
const formatCodeHTML = (code) => {
    // Code is string literal
    return "<pre>" + code + "</pre>";
};

/**
 * Runs the tests on the given workspace and returns an array of booleans, one for each test, indicating whether
 * the test passed or not
 * @param {WorkspaceSvg} workspace the workspace to run the tests on
 * @param {{}} tests the tests to run
 * @returns {any[]} an array of booleans, one for each test, indicating whether the test passed or not
 */
export const runTests = (workspace, tests) => {
    // eslint-disable-next-line no-unused-vars
    const code = getWorkspaceCode(workspace);
    let results = [];
    tests.forEach((test) => {
        let thisTestCode = code; // Need to copy, so that the code is not modified for the next test
        const inputs = test.inputs;
        inputs.forEach((input) => {
            // eslint-disable-next-line no-console
            const prompt = Object.keys(input)[0];
            const values = input[prompt];

            const inputIndex = thisTestCode.indexOf(prompt);
            // Get index of first string literal after prompt
            let inputQuote1 = thisTestCode.indexOf('"', inputIndex);
            const inputQuote2 = thisTestCode.indexOf('"', inputQuote1 + 1);

            const preStr = thisTestCode.substring(0, inputQuote1 + 1);
            const postStr = thisTestCode.substring(inputQuote2);

            thisTestCode = preStr + values[0] + postStr;

        });
        // eslint-disable-next-line no-eval
        const codeOutput = eval(thisTestCode);
        results.push(codeOutput);
    });
    return results;
};

/**
 * @param {WorkspaceSvg} workspace the workspace to get the code from
 * @returns {String} the code generated by Blockly for the current workspace
 *
 * Returns the Javascript code string generated by Blockly, with the necessary wrapping code
 */
export const getWorkspaceCode = (workspace) => {
    let code = javascript.javascriptGenerator.workspaceToCode(workspace);
    const preamble = `(function () {
    let outputString = \`\`;\n`;
    const postscript = `return outputString;
})();\n`;
    // Add a preamble and a postscript to the code.
    code = preamble + code + postscript;
    return code;
};

export const testsAccordion = (results, testsJSON) => {
    const testCaseCount = testsJSON.length;

    let accordion = '';

    for (let i = 0; i < testCaseCount; i++) {
        accordion += '<details class="card">';
        accordion += '<summary class="card-header">';
        accordion += 'Test ' + (i + 1);
        // Show if test passed or failed
        if (results[i] === testsJSON[i]['output']) {
            accordion += '<span class="badge badge-success float-right">Passed</span>';
        } else {
            accordion += '<span class="badge badge-danger float-right">Failed</span>';
        }
        accordion += '</summary>';
        accordion += '<div class="card-body pt-0 pb-0 pl-2 pr-2">';
        // eslint-disable-next-line no-loop-func
        testsJSON[i]['inputs'].forEach((input) => {
            for (const key in input) {
                accordion += '<p class="pt-2 m-0">' + key + ': </p>';
                accordion += '<pre class="mt-1 mb-0 test-input">' + input[key][0] + '</pre>';
            }
        });
        accordion += '<p class="pt-2 border-top mt-2 mb-0">Test output: </p>';
        accordion += '<pre class="mt-1 mb-0 mr-0 ml-0 test-output">' + testsJSON[i]['output'] + '</pre>';
        accordion += '<div class="p-0">';
        accordion += '<p class="pt-2 m-0">Your output: </p>';
        accordion += '<pre class="pb-2 mt-1 mb-0 ml-0 mr-0 test-output">' + results[i] + '</pre>';
        accordion += '</div>';
        accordion += '</details>';
    }

    return accordion;
};
